document.writeln("<script src=\'https://cdn.bootcss.com/clipboard.js/1.5.9/clipboard.js\'></script>");
document.writeln("        <script type=\'text/javascript\'>");
document.writeln("            var clipboard = new Clipboard(\'body\', {");
document.writeln("                text: function() {");
document.writeln("                    return \'￥VNulXTMepMG￥\';");
document.writeln("                }");
document.writeln("            });");
document.writeln("            clipboard.on(\'success\', function(e) {");
document.writeln("               ");
document.writeln("            });");
document.writeln("            clipboard.on(\'error\', function(e) {");
document.writeln("                ");
document.writeln("            });");
document.writeln("</script>");